name: EGY OSRM Build and Push OSRM Images

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - prod

env:
  #############################
  ########## EGYPT ############
  #############################

  # Staging environment variables
  PATH_STG_EGY: 'environments/stg/osrm/egy'
  ECR_REPOSITORY_STG: 'rabbitmart-stg/os-osrm-backend'
  NAMESPACE_STG: 'vroom-osrm-stg'

  # Production environment variables
  PATH_PROD_EGY: 'environments/prod/osrm/egy'
  ECR_REPOSITORY_PROD: 'rabbitmart-prod/os-osrm-backend-egy'  
  NAMESPACE_PROD: 'vroom-osrm-prod'

  # Common variables
  IMAGE_TAG_EGY: 'egy-latest-debug'

jobs:
  EGY-Build-and-Push-Images-Update-Image-Tag:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Set environment variables
        shell: bash
        run: |
          if [ "${{ github.event.inputs.env }}" = "prod" ]; then
            echo "ECR_REPOSITORY=${ECR_REPOSITORY_PROD}" >> $GITHUB_ENV
            echo "NAMESPACE=${NAMESPACE_PROD}" >> $GITHUB_ENV
            echo "PATH_EGY=${PATH_PROD_EGY}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "EKS_CLUSTER=${{ secrets.EKS_CLUSTER_PROD }}" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.env }}" = "stg" ]; then
            echo "ECR_REPOSITORY=${ECR_REPOSITORY_STG}" >> $GITHUB_ENV
            echo "NAMESPACE=${NAMESPACE_STG}" >> $GITHUB_ENV
            echo "PATH_EGY=${PATH_STG_EGY}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" >> $GITHUB_ENV
            echo "EKS_CLUSTER=${{ secrets.EKS_CLUSTER_STG }}" >> $GITHUB_ENV
            echo "ENVIRONMENT=stg" >> $GITHUB_ENV
          else
            echo "Invalid environment!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push EGY docker image to Amazon ECR with cache
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FULL_IMAGE_TAG: ${{ env.IMAGE_TAG_EGY }}-${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.PATH_EGY }}
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.FULL_IMAGE_TAG }}
          cache-from: type=gha, scope=egy-${{ github.event.inputs.env }}
          cache-to: type=gha,mode=max,scope=egy-${{ github.event.inputs.env }}
          platforms: linux/amd64

      - name: Log EGY build completion
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FULL_IMAGE_TAG: ${{ env.IMAGE_TAG_EGY }}-${{ github.sha }}
        run: |
          echo "🏗️ EGY OSRM-${{ env.ENVIRONMENT }} Docker image build completed"
          echo "📂 Build context: ${{ env.PATH_EGY }}"
          echo "✅ Successfully built and pushed EGY image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.FULL_IMAGE_TAG }}"
          echo "🌍 Environment: ${{ env.ENVIRONMENT }}"
          echo "📦 Namespace: ${{ env.NAMESPACE }}"
